---
title: "Main"
author: "Alejandro Ponce Miguela"
date: "12/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dlookr)
library(tidyverse)
```

# Carga de datos

```{r}
x_train <- read.csv(
  "../../data/training_set_features.csv",
  stringsAsFactors=TRUE
)
y_train <- read.csv(
  "../../data/training_set_labels.csv",
  stringsAsFactors=TRUE
)
y_train <- y_train[, -1]
head(x_train)
head(y_train)
```
Veamos el número de NA por filas y por columnas:

```{r}
na_by_row <- apply(is.na(x_train), 1, sum) %>%
  as.factor() %>%
  as.data.frame()
  
na_by_column <- apply(is.na(x_train), 2, sum) %>%
  as.data.frame()
na_by_column <- cbind(
  x = row.names(na_by_column),
  na_by_column  / nrow(x_train)
)

ggplot(na_by_row) + geom_bar(aes(x = .), stat = "count")
ggplot(na_by_column) + geom_bar(aes(x = x, y = .), stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

Cosa 1, ver las distribuciones de NA

```{r}
x_train_na <- x_train[, -1]
x_train_na[is.na(x_train[, -1])] <- "NA"
x_train_na <- apply(x_train_na, 2, as.factor) %>% as.data.frame()
```

```{r}
library(vcd)
tab <- table(
  cbind(x_train_na[1:15], y_train)
)
pdf("a.pdf", width = 23, height = 33)
pairs(tab, shade = TRUE, main = "THAL")
dev.off()
```






